OSNAME:=	$(shell uname)
DESTDIR?=	$(HOME)
CONFS=		$(wildcard conf.d/*.zsh)
CONFS+=		$(wildcard func.d/*.zsh)
CONFS+=		$(wildcard alias.d/*.zsh)

.PHONY: help
help: ## Показать справку.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n\nTargets:\n"} /^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-10s\033[0m %s\n", $$1, $$2 }' $(MAKEFILE_LIST)

.PHONY: build
build: clean configs	## Собрать настройки
	@echo "Complete generate new zshrc"

.PHONY: install
install: build	## Скопировать готовые настройки
	@echo copy zshrc to $(DESTDIR)/.zshrc
	@cp zshrc $(DESTDIR)/.zshrc

configs:
	@echo "Catting configs files to zshrc.."
	@[ -z "$(CONFS)" ] || { \
		for f in $(CONFS); do \
			echo "\t$$f >>"; \
			echo "# from $$f" >> zshrc; \
			cat "$$f" >> zshrc; \
		done; \
	}

clean:
	@echo '# This file is AUTOGENERATED. Do not edit!' > zshrc

